region_name       = "Type Region"
ec2_instance_type = "t2.micro"
image_id          = "AWS Image ID"
role_name         = "Role Name to be attached"
device_name       = "AWS Device Name Here"
aws_deployment_role = "IAM Role name with elevated permissions"
access_key = "AWS Access Key Here"
secret_key = "AWS Secret Key Here"